agence/agence/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('gestion/', include('gestion.urls',  namespace='gestion')),
    path('formation/', include('formation.urls', namespace='formation')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

agence/formation/urls.py
from django.urls import path, include
from .views import formation_index


app_name = 'formation'

urlpatterns = [
    path('', formation_index, name='index'),

]

agence/gestion/urls.py
from django.urls import path, include
from .views import gestion_index, gestion_service, gestion_blog, gestion_partner, gestion_contact, gestion_project



app_name = 'gestion'

urlpatterns = [
    path('', gestion_index, name='index'),
    path('service/', gestion_service, name='service'),
    path('blog/', gestion_blog, name='blog'),
    path('partner/', gestion_partner, name='partner'),
    path('contact/', gestion_contact, name='contact'),
    path('project/', gestion_project, name='project'),

]

agence/blog/models.py
from django.db import models

# Create your models here.

agence/contact/models.py
from django.db import models

# Create your models here.

agence/formation/models.py
from django.db import models


class Offres(models.Model):
    name=models.CharField(max_length=200)
    prix=models.IntegerField()
    date_come= models.DateField()
    date_end= models.DateField()
    attestation=models.BooleanField(default=True)
    pratique=models.BooleanField(default=True)
    projet=models.BooleanField(default=True)
    jours=models.IntegerField()

    def __str__(self):
        return self.name

agence/gestion/models.py
from django.db import models
import os
import random


def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)
    return name, ext


def upload_image_path(instance, filename):
    new_filename = random.randint(1, 20)
    name, ext = get_filename_ext(filename)
    final_filename = '{new_filename}{ext}'.format(new_filename=new_filename, ext=ext)
    return "product/{new_filename}/{final_filename}".format(
        new_filename=new_filename,
        final_filename=final_filename
    )


class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)


    def __str__(self):
        return self.name


class Picture(models.Model):
    title = models.CharField(max_length=100, unique=True)
    image = models.ImageField(upload_to=upload_image_path, null=True, blank=True)

    def __str__(self):
        return self.title


class Article(models.Model):
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=256, null=True, blank=True )
    body = models.TextField()
    publication = models.BooleanField(default=True)
    create_at = models.DateField(auto_now=True, null=True, blank=True)
    update_at = models.DateField(auto_now_add=True, null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    picture = models.ForeignKey(Picture, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Service(models.Model):
    name=models.CharField(max_length=100)
    detail=models.TextField()
    picto=models.CharField(max_length=250)

agence/blog/views.py
from django.shortcuts import render

# Create your views here.

agence/contact/views.py
from django.shortcuts import render

# Create your views here.

agence/formation/views.py
from django.shortcuts import render
from .models import Offres

def formation_index(request):
    offres = Offres.objects.all()
    return render(request,'offres.html', {'offres':offres} )

agence/gestion/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404
from .models import Article, Category, Picture, Service


def gestion_index(request):

    articles=Article.objects.all()
    images = Picture.objects.filter(title__startswith='about')
    services = Service.objects.all()

    return render(request, 'index.html',  {
                                            'articles':articles,
                                            'images':images,
                                            'services':services
                                           })


def gestion_service(request):
    return render(request, 'services.html', {})


def gestion_blog(request):
    return render(request, 'blogs.html', {})


def gestion_partner(request):
    return render(request, 'partners.html', {})


def gestion_contact(request):
    return render(request, 'contacts.html', {})


def gestion_project(request):
    return render(request, 'projects.html', {})

agence/templates/_include/_navbar.html
{% load static %}
<div class="navbar navbar-default navbar-fixed-top menu-top menu_dropdown">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
					<a href="index.html" class="navbar-brand"><img src="{% static 'assets/img/logo_codit.png' %}" alt="logo codit"></a>
                </div>
                <div class="navbar-collapse collapse">
                    <nav>
						<ul class="nav navbar-nav navbar-right">

							<li><a class="page-scroll" href="{% url 'gestion:index' %}">Home</a></li>
							<li><a class="page-scroll" href="{% url 'gestion:index' %}">About Us</a></li>
							<li><a class="page-scroll" href="{% url 'gestion:service' %}">Services</a></li>
							<li><a class="page-scroll" href="{% url 'gestion:partner' %}">partners</a></li>
							<li><a class="page-scroll" href="" target="_blank">projects</a>
								<ul class="sub-menu">
									<li><a href="{% url 'gestion:project' %}">Nos Réalisations</a></li>
								</ul>
							</li>
							<li><a class="page-scroll" href="#blog">Blog</a>
								<ul class="sub-menu">
									<li><a href="{% url 'gestion:blog' %}">Blogs</a></li>
								</ul>
							</li>
							<li><a class="page-scroll" href="{% url 'formation:index' %}">offres</a></li>
							<li><a class="page-scroll" href="{% url 'gestion:contact' %}">Contact</a></li>
						</ul>
					</nav>
                </div>
            </div><!--- END CONTAINER -->
        </div>

agence/templates/_include/_sidebar.html
{% load static %}

<section id="home" class="slider" style="background-image: url({% static 'assets/img/bg/codit_slide.jpg' %});  background-size:cover; background-position: center center;">
			<div class="container">
				<div class="row">
				  <div class="col-md-10 col-md-offset-1 col-sm-12 text-center">
					<div class="hero-text">
						<h2><span class="rotate">Codit Makes Everything Better | Quality Never goes out of style | The best you can get from here</span></h2>
						<p class="text-lead">Notre agence permet aux entreprises de rivaliser en ligne avec des marques plus grandes sur le même terrain.
							Vous remarquerez immédiatement une énorme différence dans vos appels entrants et votre trafic piétonnier.</p>
						<a class="btn btn-default btn-home-bg page-scroll" href="#">Get start</a>
						<a class="btn btn-default btn-home-bg page-scroll" href="#">Learn More</a>
					 </div>
				  </div><!--- END COL -->
				</div><!--- END ROW -->
			</div><!--- END CONTAINER -->
		</section>

agence/templates/_include/footer.html
{% load static %}


<!-- START VIDEO & SKILLS -->
		<div class="our_skills section-padding" style="background-image: url(assets/img/bg/skill-bg.jpg);  background-size:cover; background-position: center center;background-attachment:fixed;">
			<div class="container">
				<div class="row ">
					<div class="col-md-6 col-sm-6 col-xs-12">
						<!--
						<div class="video">
							<iframe src="https://player.vimeo.com/video/232842897"></iframe>
						</div>
						-->
					</div><!--- END COL -->
					<div class="col-md-6 col-sm-6 col-xs-12">
						<div class="skills">
							<div class="progress-bar-linear">
								<p class="progress-bar-text">html / css</p>
								<div class="progress-bar">
									<span data-percent="95"></span>
								</div>
							</div>
							<div class="progress-bar-linear">
								<p class="progress-bar-text">web design</p>
								<div class="progress-bar">
									<span data-percent="95"></span>
								</div>
							</div>
							<div class="progress-bar-linear">
								<p class="progress-bar-text">photography </p>
								<div class="progress-bar">
									<span data-percent="90"></span>
								</div>
							</div>
							<div class="progress-bar-linear">
								<p class="progress-bar-text">Graphic design </p>
								<div class="progress-bar">
									<span data-percent="75"></span>
								</div>
							</div>
							<div class="progress-bar-linear">
								<p class="progress-bar-text">Programming</p>
								<div class="progress-bar">
									<span data-percent="75"></span>
								</div>
							</div>
						</div>
					</div><!--- END COL -->
				</div><!--- END ROW -->
			</div><!--- END CONTAINER -->
		</div>
		<!-- END VIDEO & SKILLS -->

		<!-- START COUNDOWN -->
		<section class="counter_feature">
			<div class="container">
				<div class="row">
					<div class="col-md-3 col-sm-6 col-xs-12 wow fadeInLeft" data-wow-duration="1s" data-wow-delay="0.2s" data-wow-offset="0">
						<div class="counter">
							<i class="fa fa-check"></i>
							<h2 class="timer"> 2500</h2>
							<h5>Projects Finished</h5>
						</div>
					</div> <!--- END COL -->
					<div class="col-md-3 col-sm-6 col-xs-12 wow fadeInLeft" data-wow-duration="1s" data-wow-delay="0.3s" data-wow-offset="0">
						<div class="counter">
							<i class="fa fa-check"></i>
							<h2 class="timer">28256 </h2>
							<h5>Line Of Coding</h5>
						</div>
					</div><!--- END COL -->
					<div class="col-md-3 col-sm-6 col-xs-12 wow fadeInLeft" data-wow-duration="1s" data-wow-delay="0.4s" data-wow-offset="0">
						<div class="counter">
							<i class="fa fa-check"></i>
							<h2 class="timer"> 1296</h2>
							<h5>Award Won</h5>
						</div>
					</div> <!--- END COL -->
					<div class="col-md-3 col-sm-6 col-xs-12 wow fadeInLeft" data-wow-duration="1s" data-wow-delay="0.5s" data-wow-offset="0">
						<div class="counter">
							<i class="fa fa-check"></i>
							<h2 class="timer">2000</h2>
							<h5>Satisfied Clients</h5>
						</div>
					</div> <!--- END COL -->
			  </div><!--- END ROW -->
		   </div><!--- END CONTAINER -->
		</section>
		<!-- END COUNDOWN -->



<section class="footer" style="background-image: url(assets/img/bg/footer-bg.jpg);  background-size:cover; background-position: center center;background-attachment:fixed;">
			<div class="container">
				<div class="row">
					<div class="col-md-12 col-sm-12  text-center wow fadeInLeft" data-wow-duration="1s" data-wow-delay="0.2s" data-wow-offset="0">
							<div class="footer_logo">
								<a href="index.html"><img src="{% static 'assets/img/logo_codit.png' %}" alt="codit logo" /></a>
							</div>
						<div class="footer_social">
							<ul>
								<li><a class="f_facebook  wow bounceInDown" href="#"><i class="fa fa-facebook"></i></a></li>
								<li><a class="f_twitter wow bounceInDown" data-wow-delay=".1s" href="#"><i class="fa fa-twitter"></i></a></li>
								<li><a class="f_google wow bounceInDown" data-wow-delay=".2s" href="#"><i class="fa fa-google-plus"></i></a></li>
								<li><a class="f_linkedin wow bounceInDown" data-wow-delay=".3s" href="#"><i class="fa fa-linkedin"></i></a></li>
								<li><a class="f_youtube wow bounceInDown" data-wow-delay=".4s" href="#"><i class="fa fa-youtube"></i></a></li>
								<li><a class="f_skype wow bounceInDown" data-wow-delay=".5s" href="#"><i class="fa fa-skype"></i></a></li>
							</ul>
						</div>
					</div><!--- END COL -->
				</div><!--- END ROW -->
				<div class="row">
					<div class="col-md-10 col-md-offset-1 col-sm-12 col-xs-12">
						<div class="row">
							<div class="newsletter_bg">
								<div class="col-md-5 col-sm-12 col-xs-12 ">
									<h4 class="newsletter_title">Subscribe &amp; get amazing update</h4>
								</div><!-- END COL  -->
								<div class="col-md-7 col-sm-12 col-xs-12 text-center">
									<div class="signup_form">
											<!-- Replace the form action in the line below with your MailChimp embed action! -->
										<form action="http://site90.us11.list-manage.com/subscribe/post?u=599a2153f4b86cb2f92d4af3a&amp;id=26d7c26287" method="post" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
											<input type="email" name="EMAIL" class="form-control" id="mce-email" placeholder="Enter Your Email">
											<span><button type="submit" name="subscribe" class="btn btn-detault btn-newsletter-bg">Subscribe</button></span>
											<div id="mce-responses">
												<div class="response" id="mce-error-response" style="display:none"></div>
												<div class="response" id="mce-success-response" style="display:none"></div>
											</div>
										</form>
									</div>
								</div><!-- END COL  -->
							</div>
						</div>
					</div>
				</div><!-- END ROW  -->
			</div><!--- END CONTAINER -->
		</section>
		<!-- END FOOTER TOP -->

		<!-- START FOOTER TOP -->
		<footer class="footer_copyright">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<div class="copyright text-center wow zoomIn">
							<p>AGENCE CODIT - Copyright 2020. Developed by <a href="www.agencecodit.com" target="_blank">Codit</a></p>
						</div><!--- END FOOTER COPYRIGHT -->
					</div><!-- END COL  -->
				</div><!-- END ROW  -->
			</div><!--- END CONTAINER -->
		</footer>
		<!-- END FOOTER TOP -->

		<!-- Latest jQuery -->
			<script src="{% static 'assets/js/jquery-1.12.4.min.js' %}"></script>
		<!-- Latest compiled and minified Bootstrap -->
			<script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
		<!-- modernizr JS -->
			<script src="{% static 'assets/js/modernizr-2.8.3.min.js' %}"></script>
		<!-- countTo js -->
			<script src="{% static 'assets/js/jquery.inview.min.js' %}"></script>
		<!-- magnific-popup js -->
			<script src="{% static 'assets/js/jquery.magnific-popup.min.js' %}"></script>
		<!-- simple-text-rotator.min.js  -->
			<script src="{% static 'assets/simple-text-rotator/js/jquery.simple-text-rotator.min.js' %}"></script>
		<!-- jquery mixitup js -->
			<script src="{% static 'assets/js/jquery.mixitup.min.js' %}"></script>
		<!-- stellar js -->
			<script src="{% static 'assets/js/jquery.stellar.min.js' %}"></script>
		<!-- jquery appear js -->
			<script src="{% static 'assets/js/jquery.appear.js' %}"></script>
        <!--master slider-->
			<script src="{% static 'assets/master-slider/js/masterslider.min.js' %}"></script>
		<!-- owl-carousel min js  -->
			<script src="{% static 'assets/owlcarousel/js/owl.carousel.min.js' %}"></script>
		<!-- scrolltopcontrol js -->
			<script src="{% static 'assets/js/scrolltopcontrol.js' %}"></script>
		<!-- WOW - Reveal Animations When You Scroll -->
			<script src="{% static 'assets/js/wow.min.js' %}"></script>
		<!-- map js -->
			<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDwIQh7LGryQdDDi-A603lR8NqiF3R_ycA"></script>
			<script src="{% static 'assets/js/gmap3.min.js' %}"></script>
		<!-- map js -->
			<script src="{% static 'assets/js/map.js' %}"></script>
		<!-- scripts js -->
			<script src="{% static 'assets/js/scripts.js' %}"></script>
			<script type="text/javascript">
			 /*  Textrotator */
			if ($('.rotate').length > 0) {
				$(".rotate").textrotator({
					animation: "dissolve", // You can pick the way it animates when rotating through words. Options are dissolve (default), fade, flip, flipUp, flipCube, flipCubeUp and spin.
					separator: "|", //  You can define a new separator (|, &, * etc.) by yourself using this field.
					speed: 3000 // How many milliseconds until the next word show.
				});
			}
			/* End Textrotator */
			</script>

agence/templates/_include/header.html
{% load static %}
		<!-- Meta -->
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
		<!-- SITE TITLE -->

		<title>Agence codit - Agence communication & Digital</title>

		<!-- Latest Bootstrap min CSS -->
		<link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
		<!-- Google Font -->
		<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
		<link href="http://fonts.googleapis.com/css?family=Cousine:400,700" rel="stylesheet" type="text/css">
		<!-- Font Awesome CSS -->
		<link rel="stylesheet" href="{% static 'assets/fonts/font-awesome.min.css' %}">
		<!-- magnific popup CSS -->
		<link rel="stylesheet" href="{% static 'assets/css/magnific-popup.css' %}">
        <!--master slider-->
        <link rel="stylesheet" href="{% static 'assets/master-slider/style/masterslider.css' %}">
        <link rel="stylesheet" href="{% static 'assets/master-slider/skins/default/style.css' %}">
		<!--- owl carousel Css-->
		<link rel="stylesheet" href="{% static 'assets/owlcarousel/css/owl.carousel.css' %}">
		<link rel="stylesheet" href="{% static 'assets/owlcarousel/css/owl.theme.css' %}">
		<!-- Simpletextrotator css -->
        <link rel="stylesheet" href="{% static 'assets/simple-text-rotator/css/simpletextrotator.css' %}">
		<!-- animate CSS -->
		<link rel="stylesheet" href="{% static 'assets/css/animate.css' %}">
		<!-- Style CSS -->
		<link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js' %}"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js' %}"></script>
		<![endif]-->

agence/templates/blogs.html
{% extends 'layouts/base.html' %}
{% load static%}

{% block content %}




		<!-- START HOME BLOG -->
		<section id="blog" class="home_blog section-padding">
			<div class="container">
				<div class="row">
					<div class="section-title text-center">
						<h2>Latest <span>Blog</span></h2>
						<div class="line"></div>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce vitae risus nec dui venenatis dignissim. Aenean vitae metus in augue pretium ultrices. Duis dictum eget dolor vel blandit.</p>
					</div>
					<div class="col-md-6 col-sm-12 col-xs-12">
						<div class="home_single_blog">
							<img class="blog-photo" alt="" src="{% static 'assets/img/blog/blog1.jpg' %}"/>
							<div class="home_blog_text text-center wow fadeInLeft">
								 <span><i class="fa fa-eye"></i> 249 View</span><span><i class="fa fa-comments-o"></i> 08 Comment</span>
								 <h4>Blog title here</h4>
								 <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sed elit tortor. Quisque bibendum mauris velit.</p>
								<a class="btn-light-bg" href="blog-post.html">Read More</a>
							</div>
						</div><!--- END SINGLE BLOG POST -->
					</div><!--- END COL -->
					<div class="col-md-6 col-sm-12 col-xs-12">
						<div class="home_single_blog">
							<img class="blog-photo" alt="" src="{% static 'assets/img/blog/blog2.jpg' %}"/>
							<div class="home_blog_text text-center wow fadeInLeft">
								 <span><i class="fa fa-eye"></i> 249 View</span><span><i class="fa fa-comments-o"></i> 08 Comment</span>
								 <h4>Blog title here</h4>
								 <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sed elit tortor. Quisque bibendum mauris velit.</p>
								<a class="btn-light-bg" href="blog-post.html">Read More</a>
							</div>
						</div><!--- END SINGLE BLOG POST -->
					</div><!--- END COL -->
				</div><!--- END ROW -->
			</div><!--- END CONTAINER -->
		</section>
		<!-- END HOME BLOG -->

		<!-- START TESTIMONIAL -->
		<div class="client_testimonial" style="background-image: url(assets/img/bg/testimonial-bg.jpg);  background-size:cover; background-position: center center;background-attachment:fixed;">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="ms-staff-carousel">
                            <div class="master-slider" id="teamslider">
                                <div class="ms-slide">
                                    <img src="{% static 'assets/master-slider/style/blank.gif" data-src="assets/img/testimonial/1.jpg" alt=""/>
                                    <div class="ms-info text-center">
                                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sed elit tortor. Quisque bibendum mauris velit, sed tincidunt massa lacinia nec. Mauris rutrum viverra metus, vel aliquet libero eleifend eu. Sed id tempus libero, vitae porta nisi. Quisque in tincidunt elit. Sed sit amet fringilla ante. Nunc fringilla pharetra mi vitae bibendum.</p>
										<h3>Syed Ekram - <span>Project Manager</span></h3>
                                    </div>
                                </div><!--SLIDE TEAM-->
                                <div class="ms-slide">
                                    <img src="{% static 'assets/master-slider/style/blank.gif" data-src="assets/img/testimonial/2.jpg" alt=""/>
                                    <div class="ms-info text-center">
                                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sed elit tortor. Quisque bibendum mauris velit, sed tincidunt massa lacinia nec. Mauris rutrum viverra metus, vel aliquet libero eleifend eu. Sed id tempus libero, vitae porta nisi. Quisque in tincidunt elit. Sed sit amet fringilla ante. Nunc fringilla pharetra mi vitae bibendum.</p>
										<h3>Syed Ekram - <span>Project Manager</span></h3>
                                    </div>
                                </div><!--SLIDE TEAM-->
                                <div class="ms-slide">
                                    <img src="{% static 'assets/master-slider/style/blank.gif" data-src="assets/img/testimonial/3.jpg" alt=""/>
                                    <div class="ms-info text-center">
                                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sed elit tortor. Quisque bibendum mauris velit, sed tincidunt massa lacinia nec. Mauris rutrum viverra metus, vel aliquet libero eleifend eu. Sed id tempus libero, vitae porta nisi. Quisque in tincidunt elit. Sed sit amet fringilla ante. Nunc fringilla pharetra mi vitae bibendum.</p>
										<h3>Syed Ekram - <span>Project Manager</span></h3>
                                    </div>
                                </div><!--SLIDE TEAM-->
                                <div class="ms-slide">
                                    <img src="{% static 'assets/master-slider/style/blank.gif" data-src="assets/img/testimonial/4.jpg" alt=""/>
                                    <div class="ms-info text-center">
                                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sed elit tortor. Quisque bibendum mauris velit, sed tincidunt massa lacinia nec. Mauris rutrum viverra metus, vel aliquet libero eleifend eu. Sed id tempus libero, vitae porta nisi. Quisque in tincidunt elit. Sed sit amet fringilla ante. Nunc fringilla pharetra mi vitae bibendum.</p>
										<h3>Syed Ekram - <span>Project Manager</span></h3>
                                    </div>
                                </div><!--SLIDE TEAM-->
                                <div class="ms-slide">
                                    <img src="{% static 'assets/master-slider/style/blank.gif" data-src="assets/img/testimonial/5.jpg" alt=""/>
                                    <div class="ms-info text-center">
                                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sed elit tortor. Quisque bibendum mauris velit, sed tincidunt massa lacinia nec. Mauris rutrum viverra metus, vel aliquet libero eleifend eu. Sed id tempus libero, vitae porta nisi. Quisque in tincidunt elit. Sed sit amet fringilla ante. Nunc fringilla pharetra mi vitae bibendum.</p>
										<h3>Syed Ekram - <span>Project Manager</span></h3>
                                    </div>
                                </div><!--SLIDE TEAM-->
                            </div><!--- END MASTER SLIDER -->
                            <div class="ms-staff-info" id="staff-info"> </div>
                        </div><!--- END MS STAFF CAROUSEL -->
                    </div><!--- END COL -->
                </div><!--- END ROW -->
            </div><!--- END CONTAINER -->
        </div>
		<!-- END TESTIMONIAL -->




		<!-- PROMOTION -->
		<section class="buy_now">
			<div class="container text-center">
				<h3 class="buy_now_title">Your Choice Is Our Choice<a href="#" class="btn-light-bg">Purchase Now</a> </h3>
			</div><!--- END CONTAINER -->
		</section>
		<!-- END PROMOTION -->


{% endblock %}

agence/templates/index.html
{% extends 'layouts/base.html' %}
{% load static%}

{% block content %}

<section id="about" class="about-us section-padding">
			<div class="container">
				<div class="row">
					<div class="section-title text-center">
						<h2>Welcome to <span>Codit</span> </h2>
						<div class="line"></div>
								<p>Les Entreprise d’aujourd’hui ont besoin d’un partenaire fiable et compétent qui puisse être capable de leur apporter
									toutes les compétences en communication & marketing digital et mettre en place une stratégie qui
									leur assurera son objectif : notoriété, business et réputation dans un contexte en perpétuel changement.</p>

					</div>
					<div class="col-md-6 col-sm-6 col-xs-12">
						<div class="about-us-content">
							<h2>About our <span>Codit</span></h2>
							<div class="about-line"></div>
							{% for art in articles %}
								<p>{{ art.body }}</p>
							{% endfor%}

							<a class="btn-light-bg" href="#">Contactez-nous</a>
						</div>
					</div><!-- END COL -->
					{% for pic in images %}

					<div class="col-md-6 col-sm-6 col-xs-12">
						<div class="about_img">
							<img src="{{ pic.image.url}}" class="img-responsive" alt="" height="100%"/>

						</div>
					</div><!-- END COL -->
							{% endfor %}
				</div><!-- END ROW -->
			</div><!-- END CONTAINER -->
		</section>
		<!-- END ABOUT US -->

		<!-- START HOME SERVICE -->
		<section class="home_service">
			<div class="container-fliud">
				<div class="row text-center">

					{% for serv in services %}

					<div class="col-md-3 col-sm-3 col-xs-12 no-padding">
						<div class="home_single_service">
							<i class="{{ serv.picto}}"></i>
							<h4>{{ serv.name}}</h4>
							<p>{{ serv.detail}}</p>
						</div>
					</div><!-- END COL -->
					{% endfor %}
				</div><!-- END ROW -->
			</div><!-- END CONTAINER -->
		</section>
		<!-- END HOME SERVICE -->


{% endblock %}